name: surf_practice_chat_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  surf_study_jam: ^0.2.0

  cupertino_icons: ^1.0.2

  intl: ^0.17.0
  # get relative date
  timeago: ^3.3.0

  shared_preferences: ^2.0.15

  provider: ^6.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  formz: ^0.4.0
  rounded_loading_button: ^2.1.0

  maps_launcher: ^2.0.1
  geolocator: ^9.0.1

  string_to_hex: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:

  uses-material-design: true
